version: '3'
networks:
  default:
    external:
      name: server
services:
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    #ports:
    #  - "127.0.0.1:9003:9000"
